(define (calculadora op a b)
    (cond
        ((string-ci=? op "*") (* a b))
        ((string-ci=? op "+") (+ a b))
        ((string-ci=? op "-") (- a b))
        ((string-ci=? op "/") (/ a b))
        (else "Valor invalido")
    )   
)
(define (main)
    (display (calculadora "*" 5 6)) (newline)
    (display (calculadora "+" 9 6)) (newline)
    (display (calculadora "-" 9 6)) (newline)
    (display (calculadora "/" 9 6)) (newline)
    (display (calculadora "d" 9 6))
)
(main)