(define (maximoDivisor x y z)
    (cond
        ((and (= y 0) (= z 0)) x)
        ((and (= x 0) (= z 0)) y)
        ((and (= x 0) (= y 0)) z)
        ((and (> x y) (> y z)) (maximoDivisor (modulo x z) (modulo y z)  z       ))
        ((> z y)               (maximoDivisor (modulo x y)  y           (modulo z y)))
        (else                    (maximoDivisor  x           (modulo y x) (modulo z x)))
    )
)
(define (main)
    (write (maximoDivisor 38 76 760))
)
(main)