(define (bhaskara a b c)
    (list (/ (+ (* -1 b) (sqrt (- (* b b) (* 4 a c)))) (* 2 a)) 
        (/ (- (* -1 b) (sqrt (- (* b b) (* 4 a c)))) (* 2 a))
    )
)
(define (main)
    (write (bhaskara 1 -15 50))
)
(main)