(define (xor a b)
    (or (and a (not b)) (and (not a) b))
)
(define (main)
    (write (xor #t #f)) (newline)
    (write (xor #t #t)) (newline)
    (write (xor #f #f)) (newline)
    (write (xor #f #t)) (newline)
)
(main)